import Image from "next/image";
import { CommentCardGenerator } from "@/components/CommentCardGenerator";

export default function HomePage() {
    return (
        <div className="min-h-screen flex flex-col font-mono">
            {/* Header */}
            <header className="w-full border-b">
                <div className="container mx-auto px-4 py-4 flex items-center justify-between">
                    <div className="flex items-center space-x-3 bg-amber-200 p-2 rounded-lg">
                        <Image
                            src="/logo.png"
                            alt="Cavdar.fr Logo"
                            width={40}
                            height={40}
                            className="rounded-lg"
                        />
                        <div className="flex flex-col">
                            <h1 className="text-xl font-bold">
                                YouTube Comment Card
                            </h1>
                            <span className="text-xs text-gray-600 font-normal">
                                Enhanced with Puppeteer ✨
                            </span>
                        </div>
                    </div>
                </div>
            </header>

            {/* Main Content */}
            <main className="flex-1 container mx-auto px-4 py-4 md:py-8">
                <div className="max-w-5xl mx-auto">
                    <CommentCardGenerator />
                </div>
            </main>

            {/* Footer */}
            <footer className="w-full border-t mt-auto">
                <div className="container mx-auto px-4 py-6">
                    <div className="flex flex-col md:flex-row items-center justify-between gap-4">
                        <div className="flex items-center space-x-2 bg-amber-200 p-2 rounded-lg">
                            <Image
                                src="/logo.png"
                                alt="Cavdar.fr Logo"
                                width={24}
                                height={24}
                                className="rounded"
                            />
                            <span className="text-sm text-gray-600">
                                Generated by Cavdar.fr
                            </span>
                        </div>
                        <div className="text-sm text-gray-600">
                            © {new Date().getFullYear()} Cavdar.fr
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    );
}
